name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build nodebook tech
      run: |
        sudo apt-get install -y python3-setuptools
        python3 -m pip install wheel
        python3 -m pip install jupyter-repo2docker
        echo "papermill" >> requirements.txt
        jupyter-repo2docker --user-id=1001 --user-name=nbrunner --image-name=notebook-tech --no-run .
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
